### ISSUE TITLE
Update To Latest Version Of Invmenu Please!

### ISSUE THREAD

**Issue by XyloFD2** [GrosserZak/PortableCrates#9] opened 2022-12-23 02:51 UTC

**Comment by XyloFD2** [comment] 2022-12-23 02:54
![image](https://user-images.githubusercontent.com/104400758/209261620-327bda68-ffe0-4703-9718-439b4760289f.png)

**Comment by GrosserZak** [comment] 2022-12-23 12:06
This issue ia a duplicate of #8

**Closed as completed by GrosserZak** 2022-12-23 12:06 UTC
Labels: Duplicate
