### ISSUE TITLE
Crash error

### ISSUE THREAD

**Issue by Z47Developers** [GrosserZak/PortableCrates#12] opened 2023-07-14 17:59 UTC
Error: Undefined array key 0
File: plugins/PortableCrates.phar/src/GrosserZak/PortableCrates/PCManager
Line: 224
Type: ErrorException
Backtrace:
#0 plugins/PortableCrates.phar/src/GrosserZak/PortableCrates/PCManager(224): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[21] Undefined array key 0, string[94] phar:///home/container/plugins/PortableCrates.phar/src/GrosserZak/PortableCrates, int 224)
#1 plugins/PortableCrates.phar/src/GrosserZak/PortableCrates/PCManager(45): GrosserZak\PortableCrates\PCManager->getCrateItemByData(array[6])
#2 plugins/PortableCrates.phar/src/GrosserZak/PortableCrates/PCManager(39): GrosserZak\PortableCrates\PCManager->loadCrates()
#3 plugins/PortableCrates.phar/src/GrosserZak/PortableCrates/Main(26): GrosserZak\PortableCrates\PCManager->__construct(object pocketmine\utils\Config#40978)
#4 pmsrc/src/plugin/PluginBase(118): GrosserZak\PortableCrates\Main->onEnable()
#5 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#6 pmsrc/src/Server(1388): pocketmine\plugin\PluginManager->enablePlugin(object GrosserZak\PortableCrates\Main#49199)
#7 pmsrc/src/Server(1032): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#41285)
#8 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#9 pmsrc/src/PocketMine(357): pocketmine\server()
#10 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[215]     }
[216] 
[217]     /**
[218]      * This function is used to load the crate item on plugin start or when one has been updated
[219]      * (When a reward has been added/removed)
[220]      * @param array $data The config data of the crate
[221]      * @return Item The result item
[222]      */
[223]     private function getCrateItemByData(array $data) : Item {
[224]         $crateItem = StringToItemParser::getInstance()->parse($data[0]);
[225]         $crateItem->setNamedTag(CompoundTag::create()
[226]             ->setTag("PortableCrates", CompoundTag::create()
[227]                 ->setString("Name", $data["name"])
[228]                 ->setString("Id", $data["id"])
[229]             )
[230]         );
[231]         $crateItem->setCustomName(G::RESET . $data["customname"]);
[232]         $crateItem->setLore(array_merge($data["lore"], ["", G::RESET . G::GRAY . "(Click to open)", G::RESET . G::GRAY . "(Shift-Click to view rewards)"]));
[233]         return $crateItem;
[234]     }

**Comment by GrosserZak** [comment] 2023-07-16 12:36
This issue ia a duplicate of [#11](https://github.com/GrosserZak/PortableCrates/issues/11)

**Closed as completed by GrosserZak** 2023-07-16 12:36 UTC
Labels: Duplicate
